remote_theme: cotes2020/jekyll-theme-chirpy

lang: "pt-BR"
timezone: America/Sao_Paulo

title: "RPS Engenharia"
tagline: "Energia, Data Centers e Infraestrutura"

description: >-
  Consultoria em Infraestrutura Crítica e Energia.

url: "https://rpsengenharia.com"
baseurl: ""

nav:
  - title: "Sobre"
    url: /sobre/
  - title: "Serviços"
    url: /servicos/
  - title: "Contato"
    url: /contato/
  - title: "Insights"
    url: https://insights.rpsengenharia.com

github:
  username: rpsengenharia

social:
  name: "RPS Engenharia"
  email: contato@rpsengenharia.com
  links:
    - https://www.linkedin.com/company/rpsengenharia/

theme_mode: dark

avatar: /assets/img/logo.png

toc: true

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

paginate: 10

sass:
  style: compressed
